- `[x]` 1. Wipe old messages from Firestore
- `[x]` 2. Add `isLoading` state to CommandPanel
- `[x]` 3. Refactor evaluator prompt for aggressive B2B copywriting
- `[x]` 4. Create LeadChat.tsx and LeadDetail.tsx components
- `[x]` 5. Modify LeadsDashboard.tsx to implement Split-View layout
- `[x]` 6. Update page.tsx to remove global SidebarChat
- `[x]` 7. Update backend chat.ts to accept and filter by `leadId`
- `[x]` 8. Restart backend process
- `[x]` 9. Verify changes
