name: Vercel Production Auto-Push

on:
  push:
    branches:
      - main
      - master

env:
  VERCEL_ORG_ID: team_h4JhRvWvayMJYeKS0fRwU48u
  VERCEL_PROJECT_ID: prj_dbMUUwegDIGl0vfGVF2APCjvO8pU

jobs:
  deploy-to-vercel:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Production
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
